### ISSUE TITLE
Installation fails at Compatibility Compiler Test 1

### ISSUE THREAD

**Issue by everdaniel** [HathewayWill/WRF-MOSIT#47]
**Describe the bug**
I'm trying to install WRF using WRF-MOSIT on a clean AlmaLinux 9.5 server, the script fails when it reaches the "Compatibility Compiler Test 1":
```
Library Compatibility Tests
Test 1
01_fortran+c+netcdf_f.f:5: Error: Can't open included file 'netcdf.inc'
/usr/bin/ld: cannot find 01_fortran+c+netcdf_f.o: No such file or directory
/usr/bin/ld: cannot find -lnetcdff
/usr/bin/ld: cannot find -lnetcdf
collect2: error: ld returned 1 exit status
./WRF-MOSIT.sh: line 23044: ./a.out: No such file or directory
Compatibility Compiler Test 1 Failed
```

**To Reproduce**
1. Install AlmaLinux 9.5
2. Run WRF-MOSIT as per instructions in Github

**Expected behavior**
Script to finish successfully with the WRF model compiled

**Screenshots**
The script log is available here: https://gist.github.com/everdaniel/681e66e65223a70ec5cd89508a056e40

**Desktop (please complete the following information):**
 - OS: AlmaLinux 
 - Version 9.5 

**Additional context**
While running the script it failed several times as the system was missing some tools, so I had to install the following:
sudo dnf install git -y
sudo dnf install curl htop wget zip unzip
sudo dnf install epel-release
sudo dnf install tar
sudo dnf install gcc-gfortran
sudo dnf group install "Development Tools"

and I also needed to update automake and autoconf to the latest versions:
autoconf (GNU Autoconf) 2.72
automake (GNU automake) 1.16.5

**Comment by HathewayWill** [comment]
Good morning,

I an away from my computer for the next few days. I will try to work on a
solution Friday and Saturday.

**Comment by everdaniel** [comment]
No worries thank you Will, I tried to do it with the Intel compilers but received a similar error as well:
```
Environment Testing 
Test 1
ifx: error #10236: File not found: 'TEST_1_fortran_only_fixed.f'
ifx: command line error: no files specified; for help type "ifx -help"
./WRF-MOSIT.sh: line 23990: ./a.out: No such file or directory
Environment Compiler Test 1 Failed
```

full log here: https://gist.github.com/everdaniel/33ea1026e0d13b4361cd3fb7a5ade098

**Comment by HathewayWill** [comment]
@everdaniel okay it looks like there is either a sudo password issue not being authorized on the machine.  Are you the system admin for this sever and have sudo access?   

Almalinux is a tricky one but I will try to install it over the weekend on one of my spare hard drives and see what's failing.  It could be a simple fix like the checks for apt or dnf didn't work as expected.

**Comment by HathewayWill** [comment]
Centos should be supported I'll have to double check that

**Comment by HathewayWill** [comment]
> > [@everdaniel](https://github.com/everdaniel) okay it looks like there is either a sudo password issue not being authorized on the machine. Are you the system admin for this sever and have sudo access?
> 
> Yes, I'm the system admin and I also have sudo access -- should I try to launch the script as sudo?
> 
> > Almalinux is a tricky one but I will try to install it over the weekend on one of my spare hard drives and see what's failing. It could be a simple fix like the checks for apt or dnf didn't work as expected.
> 
> Oh I see, apologies I just double checked the README and it explicitily says "CentOS based systems not supported", I completely missed this bit very sorry. I'll just re-install the server and go with Ubuntu.

I think I have found the source of the problem for AlmaLinux and all other RHL based systems.  I am working on a fix now.

**Comment by everdaniel** [comment]
> > > [@everdaniel](https://github.com/everdaniel) okay it looks like there is either a sudo password issue not being authorized on the machine. Are you the system admin for this sever and have sudo access?
> > 
> > 
> > Yes, I'm the system admin and I also have sudo access -- should I try to launch the script as sudo?
> > > Almalinux is a tricky one but I will try to install it over the weekend on one of my spare hard drives and see what's failing. It could be a simple fix like the checks for apt or dnf didn't work as expected.
> > 
> > 
> > Oh I see, apologies I just double checked the README and it explicitily says "CentOS based systems not supported", I completely missed this bit very sorry. I'll just re-install the server and go with Ubuntu.
> 
> I think I have found the source of the problem for AlmaLinux and all other RHL based systems. I am working on a fix now.

Hi Will, let me know if there is any way I can help, I would be more than happy to, should I try with RockyLinux?

**Comment by HathewayWill** [comment]
Good morning,

Which version of WRF did you want to install?  WRF-ARW? Chem?

**Comment by everdaniel** [comment]
> Good morning,
> 
> Which version of WRF did you want to install?  WRF-ARW? Chem?
> […](#)

Yes Will, I was trying to install WRF-ARW

**Comment by HathewayWill** [comment]
I can send you the script to try.

**Comment by HathewayWill** [comment]
If we aren't connected on LinkedIn add me. I can send you the script to try

**Comment by everdaniel** [comment]
Awesome will do that now

**Comment by HathewayWill** [comment]
@everdaniel can i mark this solved?

**Comment by everdaniel** [comment]
Hi @HathewayWill ! thanks for checking in, I'm still not able to get it to work on AlmaLinux, I'm using AlmaLinux 9.4 (AlmaLinux-9.4-x86_64-minimal.iso) and the error I'm getting is:

```
--2025-03-12 20:54:42--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_NETCDF_MPI_tests.tar
Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9728 (9.5K) [application/x-tar]
Saving to: ‘Fortran_C_NETCDF_MPI_tests.tar’

Fortran_C_NETCDF_MPI_tests.tar                             100%[=======================================================================================================================================>]   9.50K  --.-KB/s    in 0s

2025-03-12 20:54:43 (112 MB/s) - ‘Fortran_C_NETCDF_MPI_tests.tar’ saved [9728/9728]

--2025-03-12 20:54:43--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_tests.tar
Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18944 (18K) [application/x-tar]
Saving to: ‘Fortran_C_tests.tar’

Fortran_C_tests.tar                                        100%[=======================================================================================================================================>]  18.50K  92.2KB/s    in 0.2s

2025-03-12 20:54:45 (92.2 KB/s) - ‘Fortran_C_tests.tar’ saved [18944/18944]

tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
./wrf-install.sh: line 277: 221192 Segmentation fault      (core dumped) tar -xvf Fortran_C_tests.tar -C "${WRF_FOLDER}"/Tests/Environment
tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
./wrf-install.sh: line 278: 221197 Segmentation fault      (core dumped) tar -xvf Fortran_C_NETCDF_MPI_tests.tar -C "${WRF_FOLDER}"/Tests/Compatibility



Environment Testing
Test 1
ifx: error #10236: File not found: 'TEST_1_fortran_only_fixed.f'
ifx: command line error: no files specified; for help type "ifx -help"
./wrf-install.sh: line 291: ./a.out: No such file or directory
Environment Compiler Test 1 Failed
```

for reference, I'm using the updated script that you shared with me via LinkedIn, I'm setting up another VM with AlmaLinux 9.5 to test there as well, will post the results here when done.

**Comment by HathewayWill** [comment]
> Hi [@HathewayWill](https://github.com/HathewayWill) ! thanks for checking in, I'm still not able to get it to work on AlmaLinux, I'm using AlmaLinux 9.4 (AlmaLinux-9.4-x86_64-minimal.iso) and the error I'm getting is:
> 
> ```
> --2025-03-12 20:54:42--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_NETCDF_MPI_tests.tar
> Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
> Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 9728 (9.5K) [application/x-tar]
> Saving to: ‘Fortran_C_NETCDF_MPI_tests.tar’
> 
> Fortran_C_NETCDF_MPI_tests.tar                             100%[=======================================================================================================================================>]   9.50K  --.-KB/s    in 0s
> 
> 2025-03-12 20:54:43 (112 MB/s) - ‘Fortran_C_NETCDF_MPI_tests.tar’ saved [9728/9728]
> 
> --2025-03-12 20:54:43--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_tests.tar
> Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
> Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 18944 (18K) [application/x-tar]
> Saving to: ‘Fortran_C_tests.tar’
> 
> Fortran_C_tests.tar                                        100%[=======================================================================================================================================>]  18.50K  92.2KB/s    in 0.2s
> 
> 2025-03-12 20:54:45 (92.2 KB/s) - ‘Fortran_C_tests.tar’ saved [18944/18944]
> 
> tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
> ./wrf-install.sh: line 277: 221192 Segmentation fault      (core dumped) tar -xvf Fortran_C_tests.tar -C "${WRF_FOLDER}"/Tests/Environment
> tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
> ./wrf-install.sh: line 278: 221197 Segmentation fault      (core dumped) tar -xvf Fortran_C_NETCDF_MPI_tests.tar -C "${WRF_FOLDER}"/Tests/Compatibility
> 
> 
> 
> Environment Testing
> Test 1
> ifx: error #10236: File not found: 'TEST_1_fortran_only_fixed.f'
> ifx: command line error: no files specified; for help type "ifx -help"
> ./wrf-install.sh: line 291: ./a.out: No such file or directory
> Environment Compiler Test 1 Failed
> ```
> 
> for reference, I'm using the updated script that you shared with me via LinkedIn, I'm setting up another VM with AlmaLinux 9.5 to test there as well, will post the results here when done.

Try deleting the WRF-MOSIT folder and WRF folder then git clone it down again.  I think it should be fixed with my latest update but ill double check when you send me results

**Comment by HathewayWill** [comment]
@everdaniel Use the github repo,

git clone https://github.com/HathewayWill/WRF-MOSIT.git

**Comment by everdaniel** [comment]
Hi @HathewayWill I deleted the WRF MOSIT folder, the WRF_Intel folder and launched the WRF-MOSIT.sh and I'm still getting the same error:

```
--2025-03-12 22:29:43--  https://www2.mmm.ucar.edu/wrf/OnLineTutorial/compile_tutorial/tar_files/Fortran_C_tests.tar
Resolving www2.mmm.ucar.edu (www2.mmm.ucar.edu)... 128.117.13.91
Connecting to www2.mmm.ucar.edu (www2.mmm.ucar.edu)|128.117.13.91|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18944 (18K) [application/x-tar]
Saving to: ‘Fortran_C_tests.tar’

     0K .......... ........                                   100% 94.9K=0.2s

2025-03-12 22:29:44 (94.9 KB/s) - ‘Fortran_C_tests.tar’ saved [18944/18944]

tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
./WRF-MOSIT.sh: line 24560: 298276 Segmentation fault      (core dumped) tar -xvf Fortran_C_tests.tar -C "${WRF_FOLDER}"/Tests/Environment
tar: Relink `/opt/intel/oneapi/compiler/2025.0/lib/libimf.so' with `/lib64/libm.so.6' for IFUNC symbol `cosf'
./WRF-MOSIT.sh: line 24560: 298280 Segmentation fault      (core dumped) tar -xvf Fortran_C_NETCDF_MPI_tests.tar -C "${WRF_FOLDER}"/Tests/Compatibility



Environment Testing
Test 1
ifx: error #10236: File not found: 'TEST_1_fortran_only_fixed.f'
ifx: command line error: no files specified; for help type "ifx -help"
./WRF-MOSIT.sh: line 23990: ./a.out: No such file or directory
Environment Compiler Test 1 Failed
```

**Comment by HathewayWill** [comment]
@everdaniel i'll work on this tonight

**Comment by HathewayWill** [comment]
@everdaniel 

Okay, so delete all the folders that you have created or downloaded before so that no past version of the script is being used.

then type these commands in

```
cd $HOME

git clone https://github.com/HathewayWill/WRF-MOSIT.git

cd $HOME/WRF-MOSIT

chmod 775 *.sh

./WRF-MOSIT.sh 2>&1 | tee WRF_MOSIT.log
```

**Comment by everdaniel** [comment]
@HathewayWill did as instructed, deleted everything that was created/downloaded, and ran the script again and got the following error:

```
mpif90 -ffree-form -ffree-line-length-none -o unipost.exe -fconvert=big-endian -fno-second-underscore -frecord-marker=4 -DCOMMCODE -DLINUX -DUPPLITTLEENDIAN  -fno-range-check -O3 -fallow-argument-mismatch -fallow-invalid-boz    VRBLS2D_mod.o VRBLS3D_mod.o VRBLS4D_mod.o MASKS_mod.o PMICRPH.o SOIL_mod.o CMASSI.o CTLBLK.o GRIDSPEC.o LOOKUP.o PARAMR.o RHGRD.o RQSTFLD.o xml_perl_data.o cuparm.o params.o svptbl.o get_postfilename.o grib2_module.o SET_LVLSXML.o FILL_PSETFLD.o BNDLYR.o  BOUND.o  CALCAPE.o CALDWP.o  CALDRG.o CALHEL.o  CALLCL.o  CALMCVG.o CALPOT.o  CALPW.o CALRH.o  CALRCH.o CALRH_GSD.o CALSTRM.o CALTAU.o CALTHTE.o CALVIS.o CALVIS_GSD.o CALVOR.o CALWXT.o TIMEF.o CALWXT_RAMER.o CALWXT_BOURG.o CALWXT_REVISED.o CALRH_PW.o CALWXT_EXPLICIT.o CALWXT_DOMINANT.o CLDRAD.o CLMAX.o COLLECT.o  COLLECT_LOC.o DEWPOINT.o FDLVL.o  FGAMMA.o FIXED.o  FRZLVL.o  FRZLVL2.o GET_BITS.o  GRIBIT.o INITPOST.o LFMFLD.o  MAPSSLP.o MISCLN.o MDL2STD_P.o MIXLEN.o MDL2P.o MDLFLD.o MPI_FIRST.o  MPI_LAST.o NGMFLD.o NGMSLP.o  OTLFT.o OTLIFT.o SLP_new.o SLP_NMM.o EXCH.o PARA_RANGE.o PROCESS.o INITPOST_NMM.o EXCH2.o READCNTRL.o  READ_xml.o SET_OUTFLDS.o SCLFLD.o  SERVER.o SETUP_SERVERS.o SMOOTH.o SURFCE.o SPLINE.o  TABLE.o  TABLEQ.o  TRPAUS.o  TTBLEX.o WETBULB.o WRFPOST.o CALMICT.o MICROINIT.o GPVS.o MDL2SIGMA.o ETCALC.o CANRES.o CALGUST.o WETFRZLVL.o SNFRAC.o MDL2AGL.o SNFRAC_GFS.o AVIATION.o DEALLOCATE.o CALPBL.o MDL2SIGMA2.o INITPOST_GFS.o CALRH_GFS.o LFMFLD_GFS.o CALRAD_WCLOUD_newcrtm.o MDL2THANDPV.o CALPBLREGIME.o POLEAVG.o INITPOST_NEMS.o GETNEMSNDSCATTER.o ICAOHEIGHT.o INITPOST_GFS_NEMS.o GEO_ZENITH_ANGLE.o GFIP3.o GRIDAVG.o CALUPDHEL.o MSFPS.o INITPOST_GFS_SIGIO.o AllGETHERV_GSD.o SELECT_CHANNELS.o ALLOCATE_ALL.o INITPOST_NEMS_MPIIO.o ASSIGNNEMSIOVAR.o INITPOST_GFS_NEMS_MPIIO.o INITPOST_NETCDF.o INITPOST_GFS_NETCDF.o gtg_ctlblk.o gtg_indices.o gtg_filter.o gtg_compute.o gtg_config.o map_routines.o gtg_algo.o CALVESSEL.o CALHEL2.o CALCAPE2.o  wrf_io_flags.o getVariable.o getIVariableN.o kinds_mod.o machine.o physcons.o native_endianness.o retrieve_index.o ZENSUN.o CLDFRAC_ZHAO.o GFSPOST.o GFSPOSTSIG.o GETGBANDSCATTER.o blockIO.o  -Wl,-noinhibit-exec -L/home/wrf/WRF/UPPV4.1/lib -lCRTM  -lxmlparse  -L/home/wrf/WRF/Libs/nceplibs/lib -lwrfio -lg2_v3.1.0_4 -lg2tmpl_v1.5.0 -lnemsio_d -lsigio_v2.0.1_4 -lsfcio_v1.0.0_4 -lgfsio_4 -lsp_v2.0.2_d -lw3nco_v2.0.6_4 -lw3emc_v2.2.0_4 -lbacio_4  -L/home/wrf/WRF/Libs/NETCDF/lib -lnetcdff -lnetcdf
/usr/bin/ld: cannot find grib2_module.o: No such file or directory
/usr/bin/ld: cannot find CALWXT_BOURG.o: No such file or directory
/usr/bin/ld: cannot find MISCLN.o: No such file or directory
/usr/bin/ld: cannot find MDL2STD_P.o: No such file or directory
/usr/bin/ld: cannot find READ_xml.o: No such file or directory
/usr/bin/ld: cannot find SET_OUTFLDS.o: No such file or directory
/usr/bin/ld: cannot find WRFPOST.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_GFS.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_NEMS.o: No such file or directory
/usr/bin/ld: cannot find GETNEMSNDSCATTER.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_GFS_NEMS.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_GFS_SIGIO.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_NEMS_MPIIO.o: No such file or directory
/usr/bin/ld: cannot find INITPOST_GFS_NEMS_MPIIO.o: No such file or directory
/usr/bin/ld: cannot find GFSPOSTSIG.o: No such file or directory
/usr/bin/ld: cannot find -lwrfio
/usr/bin/ld: cannot find -lg2_v3.1.0_4
/usr/bin/ld: cannot find -lg2tmpl_v1.5.0
/usr/bin/ld: cannot find -lnemsio_d
/usr/bin/ld: cannot find -lsigio_v2.0.1_4
/usr/bin/ld: cannot find -lsfcio_v1.0.0_4
/usr/bin/ld: cannot find -lgfsio_4
/usr/bin/ld: cannot find -lsp_v2.0.2_d
/usr/bin/ld: cannot find -lw3nco_v2.0.6_4
/usr/bin/ld: cannot find -lw3emc_v2.2.0_4
/usr/bin/ld: cannot find -lbacio_4
collect2: error: ld returned 1 exit status
make: [makefile_dtc:93: unipost.exe] Error 1 (ignored)
/bin/cp unipost.exe /home/wrf/WRF/UPPV4.1/exec
/bin/cp: cannot stat 'unipost.exe': No such file or directory
make: [makefile_dtc:94: unipost.exe] Error 1 (ignored)
ls: cannot access './*.exe': No such file or directory
Missing one or more expected files. Exiting the script.
Please contact script authors for assistance, press 'Enter' to exit script.
```

the full log is available here if you need it:
[https://gist.github.com/everdaniel/13c32a13a9201fee22ba5df96b099497](https://gist.github.com/everdaniel/13c32a13a9201fee22ba5df96b099497)

**Comment by HathewayWill** [comment]
@everdaniel 

Good news this is a different error than before.  This is related to UPP having a cloning issue from their website, Sometimes their site is bad and doesn't download the files needed.  The files are 12 years old so they don't always access them right.

If you have the time you can delete the WRF folder then run it again and see if it comes up with that error again.  I'll also make a change where it can check for the files it needs before kicking the error that stops it.  That will take me a little time.

Alternatively you can remove the upp portion from the WRF-MOSIT script if you don't need it.

Again I apologize for the issues you're having.  A lot of the pre and post processors are extremely old and don't always work the way they should on newer compilers

**Comment by HathewayWill** [comment]
made a few changes today, hopefully they work for you.

Same instructions, delete..reclone..try again

**Comment by everdaniel** [comment]
@HathewayWill sorry for the delayed response, awesome sounds good! I'll try again and report back

**Comment by everdaniel** [comment]
@HathewayWill I was finally able to successfully compile WRF on AlmaLinux:

```
WPS_GEOG_LOW_RES/topo_gmted2010_5m/01801-02400.01201-01800
WPS_GEOG_LOW_RES/topo_gmted2010_5m/03601-04200.01201-01800
Install Start Time: Fri Mar 14 15:00:15 UTC 2025
Install End Time: Fri Mar 14 21:46:28 UTC 2025
Install Duration: 6 hours 46 minutes 13 seconds
```

in the end I had to comment out the entire sections for UPP install.

Regarding the Intel compile issue, I need to wait for WRF version 4.7 to try again with Intel right?

**Comment by HathewayWill** [comment]
For Intel yes 4.7.0 release.

I'll try and figure out what's going on with UPP and almalinux.  I got it
to work on my side so I need investigate it more.

**Comment by HathewayWill** [comment]
@everdaniel can we close this issue?

**Comment by everdaniel** [comment]
Hi @HathewayWill sure we can, the new version of WRF-MOSIT has the UPP stuff taken out right?
